# config/routes.yaml
app_home:
  path: /
  controller: App\Controller\DashboardController::index
  methods: GET

app_login:
  path: /login
  controller: App\Controller\AuthenticationController::login
  methods: [GET, POST]

app_register:
  path: /register
  controller: App\Controller\AuthenticationController::register
  methods: [GET, POST]

app_logout:
  path: /logout

app_dashboard:
  path: /dashboard
  controller: App\Controller\DashboardController::index
  methods: GET

admin_dashboard:
  path: /admin/dashboard
  controller: App\Controller\DashboardController::adminDashboard
  methods: GET

manager_dashboard:
  path: /manager/dashboard
  controller: App\Controller\DashboardController::managerDashboard
  methods: GET

owner_dashboard:
  path: /owner/dashboard
  controller: App\Controller\DashboardController::ownerDashboard
  methods: GET

tenant_dashboard:
  path: /tenant/dashboard
  controller: App\Controller\DashboardController::tenantDashboard
  methods: GET